#application-credentials.yml  파일을 만들어 다음 값들을 저장하자.
#Db_User_Name , Db_User_PassWord , Db_URL ,Db_Name


server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://${Db_URL}/${Db_Name}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${Db_User_Name}
    password: ${Db_User_PassWord}

  jpa:
    hibernate:
      #ddl-auto: create
      #ddl-auto: update
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
        #dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    #database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    database: mysql
    generate-ddl: false
    #open-in-view: false


  mvc:
    path match:
      matching-strategy: ant_path_matcher

  config.import: classpath:application-credentials.yml
    profiles:
      active: credentials
      include:
        - credentials

# cors 설정
cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600
